# docker image [gcp]
FROM ubuntu:20.04

# using root user
USER root:root

#instalando dependencias do backend(api nodejs e banco mongo)
RUN apt-get update && apt-get install -y nodejs

RUN apt-get update && apt-get install -y mongodb

# criando arvore de arquivos backend
RUN mkdir -p /locafastBackend

# copiando arvore de arquivos backend
COPY ./locaFastApi/ /locafastBackend/

# setando pasta de start api
WORKDIR /locafastBackend

# ordem sequencial de execuçao
RUN cd locaFastApi/src
RUN sudo systemctl start mongod
RUN npm start

#Build docker project *Na pasta locaFastApi*:
# docker build -t nodejs-app .

#Testing de backend online:
#docker run -it -p 3000:3000 nodejs-app

#Para fase de proddutização a imagem pode ser versionado no proṕrio github e armazenada no DockerHub em uma conta real

# user
#USER 1001